// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: transaction_fee.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.MultiToken {

  #region Events
  public partial class TransactionFeeCharged : aelf::IEvent<TransactionFeeCharged>
  {
    public global::System.Collections.Generic.IEnumerable<TransactionFeeCharged> GetIndexed()
    {
      return new List<TransactionFeeCharged>
      {
      };
    }

    public TransactionFeeCharged GetNonIndexed()
    {
      return new TransactionFeeCharged
      {
        Symbol = Symbol,
        Amount = Amount,
      };
    }
  }

  public partial class ResourceTokenCharged : aelf::IEvent<ResourceTokenCharged>
  {
    public global::System.Collections.Generic.IEnumerable<ResourceTokenCharged> GetIndexed()
    {
      return new List<ResourceTokenCharged>
      {
      };
    }

    public ResourceTokenCharged GetNonIndexed()
    {
      return new ResourceTokenCharged
      {
        Symbol = Symbol,
        Amount = Amount,
        ContractAddress = ContractAddress,
      };
    }
  }

  public partial class ResourceTokenOwned : aelf::IEvent<ResourceTokenOwned>
  {
    public global::System.Collections.Generic.IEnumerable<ResourceTokenOwned> GetIndexed()
    {
      return new List<ResourceTokenOwned>
      {
      };
    }

    public ResourceTokenOwned GetNonIndexed()
    {
      return new ResourceTokenOwned
      {
        Symbol = Symbol,
        Amount = Amount,
        ContractAddress = ContractAddress,
      };
    }
  }

  #endregion
}
#endregion

